# Generated by Django 3.2.15 on 2022-11-24 10:30

from django.db import migrations
import people.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=people.fields.UncertainDateField(blank=True),
        ),
    ]
